---

# Устанавливаем PostgreSQL
#---------------------------------------------
- name: Install PostgreSQL 14
  hosts: test-vm
  tasks:
    - name: get lsb-release
      command: "lsb_release -cs"
      register: release

    - name: print release
      debug:
        msg: 'Ubuntu distr is {{ release.stdout }}'

    - name: Add an Apt signing key, uses whichever key is at the URL
      become: true
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: add repository
      become: true
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ release.stdout }}-pgdg main"
        state: present

    - name: Update the repository cache and install PostgreSQL-14
      become: true
      apt:
        name: postgresql-14
        state: latest
        update_cache: yes

    - name: Enable service
      become: true
      systemd:
        name: postgresql
        enabled: true

    - name: Set free local access to psql
      become: true
      command: sed -i s/peer/trust/ /etc/postgresql/14/main/pg_hba.conf

    - name: Start service
      become: true
      systemd:
        name: postgresql
        state: restarted


# Устанавливаем PGAdmin
#---------------------------------------------
- name: Install PGAdmin
  hosts: test-vm
  tasks:
    - name: Add apt-key
      become: true
      apt_key:
        url: https://www.pgadmin.org/static/packages_pgadmin_org.pub
        state: present

    - name: Add repository
      become: true
      apt_repository:
        repo: "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/{{ release.stdout }} pgadmin4 main"
        state: present

    - name: Install PGAdmin
      become: true
      apt:
        name: pgadmin4
        state: latest
        update_cache: yes

    - name: Copy pgadmin_setup.sh
      become: true
      template:
        src: pgadmin_setup.sh.j2
        mode: 0755
        dest: /opt/pgadmin_setup.sh

    - name: Setup PGAdmin Web mode
      become: true
      command: /opt/pgadmin_setup.sh


- name: Create Database and filling data
  hosts: test-vm
  tasks:
    - name: Copy script
      become: true
      template:
        src: create_base.sh.j2
        mode: 0755
        dest: /opt/create_base.sh

    - name: Start script
      become: true
      command: /opt/create_base.sh


# Настраиваем бэкапы
#---------------------------------------------
- name: Setup backups
  hosts: test-vm
  tasks:
    - name: Copy psql_backup.sh
      become: true
      template:
        src: psql_backup.sh.j2
        mode: 0755
        dest: /opt/psql_backup.sh

    - name: Setup backups
      become: true
      command: /opt/psql_backup.sh

    - name: Copy psql_reindex_vacuum.sh
      become: true
      template:
        src: psql_reindex_vacuum.sh.j2
        mode: 0755
        dest: /opt/psql_reindex_vacuum.sh

    - name: Setup reindex
      become: true
      command: /opt/psql_reindex_vacuum.sh

    - name: Copy backup_cron.sh
      become: true
      template:
        src: backup_cron.sh.j2
        mode: 0755
        dest: /opt/backup_cron.sh

    - name: Setup bcakup cron
      become: true
      command: /opt/backup_cron.sh


# Настраиваем мониторинг базы с помощью PGDash
#---------------------------------------------
- name: Configure PGDash monitoring
  hosts: test-vm
  tasks:
    - name: Copy pgdash_setup.sh
      become: true
      template:
        src: pgdash_setup.sh.j2
        mode: 0755
        dest: /opt/pgdash_setup.sh

    - name: Setup backups
      become: true
      command: /opt/pgdash_setup.sh
