---

# Устанавливаем Docker и Docker Compose
#---------------------------------------------
- name: Installing Docker and Docker Compose
  hosts: test-vm
  tasks:
    - name: get lsb-release
      command: "lsb_release -cs"
      register: release

    - name: print release
      debug:
        msg: 'Ubuntu distr is {{ release.stdout }}'

    - name: Add an Apt signing key, uses whichever key is at the URL
      become: true
      command: /bin/bash -c 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

    - name: add repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"
        state: present

    - name: Install packages
      become: true
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-ce
          - docker-ce-cli
          - containerd.io 
          - docker-compose-plugin
          - inotify-tools
        state: latest
        update_cache: yes

    - name: Enable service
      become: true
      systemd:
        name: docker
        enabled: true

    - name: Start service
      become: true
      systemd:
        name: docker
        state: started

    - name: install docker-compose
      become: true
      get_url: 
        url: https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755

# Копируем скрипты и конфиг-файлы
#--------------------------------
- name: Copy scripts and configs
  hosts: test-vm
  tasks:
    - name: Create Folders
      become: true
      command: /bin/bash -c 'mkdir -p /opt/next-app; mkdir -p /opt/next-app/scripts; mkdir -p /opt/next-app/docker-deploy'

    - name: Copy Dockerfile
      become: true
      template:
        src: Dockerfile.j2
        mode: 0644
        dest: /opt/next-app/docker-deploy/Dockerfile

    - name: Copy docker-compose.yml
      become: true
      template:
        src: docker-compose.yml.j2
        mode: 0644
        dest: /opt/next-app/docker-deploy/docker-compose.yml

    - name: Copy fill_code.sh
      become: true
      template:
        src: fill_code.sh.j2
        mode: 0755
        dest: /opt/next-app/docker-deploy/fill_code.sh

    - name: Copy dev-loop.sh.j2
      become: true
      template:
        src: dev-loop.sh.j2
        mode: 0755
        dest: /opt/next-app/scripts/dev-loop.sh

    - name: Copy rebuild.sh.j2
      become: true
      template:
        src: rebuild.sh.j2
        mode: 0755
        dest: /opt/next-app/scripts/rebuild.sh


# Запускаем сервисы
#-------------------------------------------------------------
- name: Start services
  hosts: test-vm
  tasks:
    - name: Create dev-loop storage
      become: true
      command: /bin/bash -c '/opt/next-app/scripts/dev-loop.sh'

    - name: Docker Compose UP!
      become: true
      shell: docker-compose up --build --detach
      args:
         chdir: /opt/next-app/docker-deploy

    - name: Start rebuild waiting now
      become: true
      command: /bin/bash -c '/opt/next-app/scripts/rebuild.sh > /dev/null 2>&1 &'
      async: 10
      poll: 0
